print('adding a file using github')
print('remember to git->add')
print('then commit file')
print('write a message and commit and push')
print('---')
print('deleting a file of github')
print('make sure that is in the local repo and delete it')
print('commit file with the deleted file selected')
print('write a message such as deleted file, commit and push')
